/**
 * QC Config APIs
 * Backend prefix: /api/qc/config
 */
import { del, get, post, put } from './client';
import type { PageData } from './client';
import type { WorkstationConfig, StationConfig, WireHarnessTypeConfig, TerminalConfig } from '../types/qcConfig';

/** Workshop DTO */
export interface QcWorkshopVO {
  code: string;
  name: string;
  location?: string;
}

// ---------- 1.1 workshops /api/qc/config/workshops ----------

/** Query workshop list */
export function getWorkshopConfigListApi() {
  return get<QcWorkshopVO[]>('qc/config/workshops');
}

export function createWorkshopConfigApi(body: { code: string; name: string; location?: string }) {
  return post<null>('qc/config/workshops', body);
}

export function updateWorkshopConfigApi(code: string, body: Partial<QcWorkshopVO>) {
  return put<null>(`qc/config/workshops/${encodeURIComponent(code)}`, body);
}

export function deleteWorkshopConfigApi(code: string) {
  return del<null>(`qc/config/workshops/${encodeURIComponent(code)}`);
}

// ---------- 1.2 workstations /api/qc/config/workstations ----------

/** Query workstation list with optional filters and pagination */
export function getWorkstationConfigListApi(params?: { keyword?: string; workshopCode?: string; pageNum?: number; pageSize?: number }) {
  return get<PageData<WorkstationConfig>>('qc/config/workstations', params as Record<string, string | number | undefined>);
}

export function createWorkstationConfigApi(body: Omit<WorkstationConfig, 'id'> & { id?: number | string }) {
  return post<{ id: number }>('qc/config/workstations', body);
}

/** Update workstation by id (id can be number|string) */
export function updateWorkstationConfigApi(id: number | string, body: Partial<WorkstationConfig>) {
  return put<null>(`qc/config/workstations/${String(id)}`, body);
}

export function deleteWorkstationConfigApi(id: number | string) {
  return del<null>(`qc/config/workstations/${String(id)}`);
}

// ---------- 1.3 stations /api/qc/config/stations ----------

/** Station DTO used by list API */
export interface StationConfigVO extends StationConfig {
  id?: number;
}

export function getStationConfigListApi(params?: { workstationId?: string; pageNum?: number; pageSize?: number }) {
  return get<PageData<StationConfigVO>>('qc/config/stations', params as Record<string, string | number | undefined>);
}

export function createStationConfigApi(body: StationConfig) {
  return post<{ id: number }>('qc/config/stations', body);
}

/** Update station by numeric id */
export function updateStationConfigApi(id: number, body: Partial<StationConfig>) {
  return put<null>(`qc/config/stations/${id}`, body);
}

export function deleteStationConfigApi(id: number) {
  return del<null>(`qc/config/stations/${id}`);
}

// ---------- 1.4 wire-harness-types /api/qc/config/wire-harness-types ----------

/** Query wire harness type list */
export function getWireHarnessTypeConfigListApi() {
  return get<PageData<WireHarnessTypeConfig> | WireHarnessTypeConfig[]>('qc/config/wire-harness-types');
}

export function createWireHarnessTypeConfigApi(body: Omit<WireHarnessTypeConfig, 'id'> & { id?: number | string }) {
  return post<{ id: number }>('qc/config/wire-harness-types', body);
}

/** Update wire harness type by id (number|string) */
export function updateWireHarnessTypeConfigApi(id: number | string, body: Partial<WireHarnessTypeConfig>) {
  return put<null>(`qc/config/wire-harness-types/${id}`, body);
}

export function deleteWireHarnessTypeConfigApi(id: number | string) {
  return del<null>(`qc/config/wire-harness-types/${id}`);
}

// ---------- 1.5 terminals /api/qc/config/terminals ----------

export function getTerminalConfigListApi(params?: { workstationId?: string; pageNum?: number; pageSize?: number }) {
  return get<PageData<TerminalConfig>>('qc/config/terminals', params as Record<string, string | number | undefined>);
}

/** Create terminal, id is optional and usually generated by backend */
export function createTerminalConfigApi(body: Omit<TerminalConfig, 'id'> & { id?: number | string }) {
  return post<{ id: number | string }>('qc/config/terminals', body);
}

/** Update terminal by id (number|string, supports Snowflake string id) */
export function updateTerminalConfigApi(id: number | string, body: Partial<TerminalConfig>) {
  return put<null>(`qc/config/terminals/${String(id)}`, body);
}

export function deleteTerminalConfigApi(id: number | string) {
  return del<null>(`qc/config/terminals/${String(id)}`);
}
